baseurl: /curso
highlighter: pygments
layout: default
lessons: 
  - 
    number: 1
    title: Introducción
  - 
    number: 2
    title: "Variables y números"
  - 
    number: 3
    title: "Tipos de datos"
  - 
    number: 4
    title: "Control de flujo"
  - 
    number: 5
    title: "Funciones"
